### ISSUE TITLE
Your Discord bot token is public.

### ISSUE THREAD

**Issue by lauriys** [0xB4DC0FF33/NaBot#1]

**Comment by 0xB4DC0FF33** [comment]
Thanks i will correct it soon, the bot is currently unfinished, I just have to pass the repository in public mode to access w/ a host service ^^'

**Comment by 0xB4DC0FF33** [comment]
next i will do a config file with infos (like tokens etc.....) for now it's just for testing ^^

**Comment by lauriys** [comment]
your token is still live, revoke it.
